### ISSUE TITLE
Husky

### ISSUE THREAD

**Issue by samuelfernandez** [ng-easy/platform#113]
* Prettier
* Conventional Commits

https://github.com/samuelfernandez/portfolio/wiki/13.-Semantic-release

**Comment by samuelfernandez** [comment]
Documentation:

* https://dev.bleacherreport.com/how-we-use-commitizen-to-clean-up-commit-messages-a16790dcd2fd
* https://github.com/semantic-release/semantic-release

Install tooling:

```shell
npm install commitizen cz-conventional-changelog @commitlint/cli @commitlint/config-conventional semantic-release --save-dev
npx commitizen init cz-conventional-changelog --save-dev --save-exact
```

To configure it create file `.cz.json`:

```json
{
   "path": "./node_modules/cz-conventional-changelog"
}
```

And `commitlint.config.js`:

```js
module.exports = { extends: ['@commitlint/config-conventional'] };
```

Then update Husky to validate commit messages with file `husky.config.js`:

```js
module.exports = {
   hooks: {
      'commit-msg': 'commitlint -E HUSKY_GIT_PARAMS',
      'pre-commit': 'lint-staged'
   }
};
```

And then an extra file for [semantic release](https://github.com/semantic-release/semantic-release) `.releaserc.json`:

```json
{
   "branch": "master",
   "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github"
   ]
}
```

And finnally add a couple of scripts to `package.json`:

```json
   "version": "0.0.0-development",
   "scripts": {
      "commit": "git-cz",
      "semantic-release": "semantic-release"
   }
```

Then when doing a commit just call:

```shell
git cz
npm run commit
```

And finally to release a new Github version after every release we update `.travis.yml`:

```yml
      - stage: release # Release to PRD environment
        env: URL=https://samuel-fernandez.herokuapp.com/ # Here we need to make it explicit
        if: (NOT type = pull_request) AND branch = master
        script: skip # Default script is npm test, which we want to skip
        deploy:
           - provider: heroku
             app: $HEROKU_APP_PRD # This deployment is the release
             api_key:
                - $HEROKU_TOKEN # Generated running heroku authorizations:create
           - provider: script
             skip_cleanup: true
             script:
                - npx semantic-release
```

See the [generated code](https://github.com/samuelfernandez/portfolio/tree/v0.2.0). Related PR [#48](https://github.com/samuelfernandez/portfolio/pull/48) [#52](https://github.com/samuelfernandez/portfolio/pull/52).
