### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by samuelfernandez** [ng-easy/platform#130]
## 12.1. Optimize express server

Install some utilities to fine tweak our express server:

```shell
yarn add compression helmet is-heroku heroku-ssl-redirect morgan serve-favicon
```

Then update `server.js` file to use these tweaks:

```js
const path = require('path');
const fs = require('fs');
const express = require('express');
const favicon = require('serve-favicon');
const morgan = require('morgan');
const isHeroku = require('is-heroku');
const sslRedirect = require('heroku-ssl-redirect');
const helmet = require('helmet');
const compression = require('compression');

// ...

// Serve favicon
app.use(favicon(path.join(SERVE_FOLDER, 'favicon.ico')));

// Log requests
app.use(morgan('dev'));

// Redirect to https if running in production
if (isHeroku) {
   app.use(sslRedirect());
}

// Secure app
app.use(
   helmet({
      crossdomain: true,
      referrerPolicy: { policy: 'same-origin' }
   })
);

// GZIP all assets
app.use(compression());

// ...
```

Just with these tweaks we were able to improve performance by a +10% in the lighthouse report and by a +20% in the PageSpeed Inisghts report. The two main improvements where the redirection to https and compression of assets.

Documentation: https://developers.google.com/web/tools/lighthouse/audits/text-compression

Related PR [#43](https://github.com/samuelfernandez/portfolio/pull/43).

## 12.2. Optimize CSS delivery

Documentation:

* https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery
* https://developers.google.com/web/tools/lighthouse/audits/unused-css
* https://developers.google.com/web/tools/lighthouse/audits/minify-css

To optimize CSS we need to:

* Extract CSS needed for initial render and inline it.
* Remove CSS unused by the app, since usually CSS libraries include much more than used.
* Defer the rest of the CSS to a later time.
* Minify source files.

First we'll create a task that goes through all apps in `angular.json` and execute the critical CSS extranction using library `critical`.

```shell
yarn add -D critical fs-extra gulp-cheerio
```

Then create the task in `tasks/optimize-critical.js`:

```js
const path = require('path');
const gulp = require('gulp');
const critical = require('critical');
const fs = require('fs-extra');
const cheerio = require('gulp-cheerio');
const { applications } = require('../lib/angular');

// Configuration for critical, with options inline and extract, checking for iPhone and Desktop sizes
const processCritical = (baseDir, src) =>
   critical.generate({
      inline: true,
      extract: true,
      base: baseDir,
      src: src,
      dest: src,
      dimensions: [
         {
            height: 736,
            width: 414
         },
         {
            height: 1200,
            width: 1920
         }
      ],
      penthouse: {
         puppeteer: {
            args: ['--no-sandbox', '--disable-setuid-sandbox']
         }
      }
   });

const generateTask = (app) => `optimize:critical:${app.name}:generate`;
const cleanupTask = (app) => `optimize:critical:${app.name}:cleanup`;

// Generate tasks: Uses critical to process critical CSS path.
// It produces as output the generated file and extracted stylesheets
applications.forEach((app) => {
   gulp.task(generateTask(app), () => processCritical(app.outputPath, 'index.html'));
});

// Cleanup task: Replaces the old css files by new ones that don't contain the extracted css
applications.forEach((app) => {
   gulp.task(cleanupTask(app), () => {
      const index = path.resolve(app.outputPath, 'index.html');
      return gulp
         .src(index, { base: './' })
         .pipe(
            cheerio(($) => {
               // Keyed CSS that will be replaced
               const styleReplacements = {};
               const styleMatch = /(styles\..+)\..+(\.css)/;

               // Method to replace the href
               const substituteHref = (index, element) => {
                  const style = $(element);
                  const href = style.attr('href');

                  if (styleMatch.test(href)) {
                     const replaceHref = href.replace(styleMatch, '$1$2');
                     styleReplacements[href] = replaceHref;
                     style.attr('href', replaceHref);
                  }
               };

               // Cleanup tags <link rel="preload" href="styles.*.*.css" as="style"> and <link rel="stylesheet">
               $('link[as="style"]').each(substituteHref);
               $('link[rel="stylesheet"]').each(substituteHref);

               // Rename the css with extracted critical
               for (let href in styleReplacements) {
                  fs.removeSync(path.join(app.outputPath, styleReplacements[href]));
                  fs.renameSync(path.join(app.outputPath, href), path.join(app.outputPath, styleReplacements[href]));
               }
            })
         )
         .pipe(gulp.dest('./'));
   });
});

// Optimize critical task
const tasks = applications.map((app) => gulp.series(generateTask(app), cleanupTask(app)));
gulp.task('optimize:critical', gulp.parallel(...tasks));
```

And then remove unused CSS and minify output files. It is done at `tasks/optimize-css.js`:

```js
const path = require('path');
const gulp = require('gulp');
const postcss = require('gulp-postcss');
const cssnano = require('cssnano');
const purify = require('gulp-purifycss');
const { applications } = require('../lib/angular');

const cssTask = (app) => `optimize:css:${app.name}`;

// Optimize task for css files. It leaves only css classes present in src files, and minimizes the output.
applications.forEach((app) => {
   const cssPath = path.join(app.outputPath, '*.css');
   const jsPath = path.join(app.outputPath, '*.js');
   const htmlPath = path.join(app.outputPath, '*.html');

   gulp.task(cssTask(app), () =>
      gulp
         .src(cssPath, { base: './' })
         .pipe(
            purify([jsPath, htmlPath], {
               minify: true
            })
         )
         .pipe(postcss([cssnano({ preset: 'advanced' })]))
         .pipe(gulp.dest('./'))
   );
});

const tasks = applications.map((app) => cssTask(app));
gulp.task('optimize:css', gulp.parallel(...tasks));
```

Related PR [#44](https://github.com/samuelfernandez/portfolio/pull/44) [#45](https://github.com/samuelfernandez/portfolio/pull/45).

## 12.3. Optimize HTML

To optimize the delivery of an Angular app, this modifications are applied to minimize the load time:

*  Inline runtime script
*  Move main and polyfill scripts to head and mark them as defer. This makes that they are fetched earlier.

This minimizes the critical request depth.

The task that handles this is in `tasks/optimize-html.js`:

```js
const path = require('path');
const gulp = require('gulp');
const cheerio = require('gulp-cheerio');
const replace = require('gulp-replace');
const inline = require('gulp-inline-source');
const postcss = require('gulp-html-postcss');
const cssnano = require('cssnano');
const { applications } = require('../lib/angular');

/**
 * To optimize the delivery of an Angular app, this modifications are applied to minimize the load time:
 *    - Inline runtime script
 *    - Move main and polyfill scripts to head and mark them as defer. This makes that they are fetched earlier.
 *
 * This minimizes the critical request depth.
 */
const processScripts = ($) => {
   $('script[type="text/javascript"]').each((index, element) => {
      const script = $(element);
      const src = script.attr('src');

      if (/(runtime)\..*\.js/.test(src)) {
         script.attr('inline', '');
      }

      if (/(main|polyfills)\..*\.js/.test(src)) {
         script.attr('defer', '');
         $('head').append(script); // Move into head
      }
   });
};

const htmlTask = (app) => `optimize:html:${app.name}`;

// Optimize task for index.html
applications.forEach((app) => {
   const index = path.resolve(app.outputPath, 'index.html');

   gulp.task(htmlTask(app), () =>
      gulp
         .src(index, { base: './' })
         .pipe(postcss([cssnano({ preset: 'advanced' })])) // Minify inlined CSS
         .pipe(cheerio(processScripts)) // Mark scripts to be inlined
         .pipe(replace('inline=""', 'inline'))
         .pipe(inline())
         .pipe(gulp.dest('./'))
   );
});

const tasks = applications.map((app) => htmlTask(app));
gulp.task('optimize:html', gulp.parallel(...tasks));
```

Related PR [#45](https://github.com/samuelfernandez/portfolio/pull/45).

## 12.4. Optimize images with [imagemin](https://github.com/imagemin/imagemin)

Task to optimize images:

```js
const path = require('path');
const gulp = require('gulp');
const imagemin = require('gulp-imagemin');
const imageminMozjpeg = require('imagemin-mozjpeg');
const { applications } = require('../lib/angular');

const imagesTask = (app) => `optimize:images:${app.name}`;

// Minify and optimize images.
applications.forEach((app) => {
   const assets = path.join(app.outputPath, 'assets', '*.{png,jpg,jpeg,svg,gif}');

   gulp.task(imagesTask(app), () =>
      gulp
         .src(assets, { base: './' })
         .pipe(
            imagemin(
               [
                  imageminMozjpeg({ progressive: true, quality: 85 }),
                  imagemin.gifsicle({ interlaced: true }),
                  imagemin.optipng({ optimizationLevel: 5 }),
                  imagemin.svgo({
                     plugins: [{ removeViewBox: true }, { cleanupIDs: false }]
                  })
               ],
               { verbose: true }
            )
         )
         .pipe(gulp.dest('./'))
   );
});

const tasks = applications.map((app) => imagesTask(app));
gulp.task('optimize:images', gulp.parallel(...tasks));
```

Documentation: https://developers.google.com/web/tools/lighthouse/audits/optimize-images

Related PR [#45](https://github.com/samuelfernandez/portfolio/pull/45).

See the [generated code](https://github.com/samuelfernandez/portfolio/tree/v0.0.12).

## 12.5. Optimize font delivery

For this we need to download the fonts in the `assets` folder. Then the loading process can be optimized.

In `src/index.html`:

```diff
- <link rel="dns-prefetch" href="https://fonts.googleapis.com">
- <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">
+ <link rel="preload" href="/assets/fonts/montserrat-v12-latin-300.woff2" as="font" type="font/woff2" crossorigin="anonymous">
+ <link rel="preload" href="/assets/fonts/montserrat-v12-latin-600.woff2" as="font" type="font/woff2" crossorigin="anonymous">
- <script>WebFontConfig = { google: { families: ['Montserrat'] } };</script>
- <script async src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
```

Then we create the CSS for fonts at `src/scss/_fonts.scss` with [Google WebFonts Helper](https://google-webfonts-helper.herokuapp.com/fonts/montserrat?subsets=latin):

```scss
/* montserrat-300 - latin */
@font-face {
   font-family: 'Montserrat';
   font-style: normal;
   font-weight: 300;
   font-display: swap;
   src: local('Montserrat Light'), local('Montserrat-Light'),
      url('/assets/fonts/montserrat-v12-latin-300.woff2') format('woff2'),
      url('/assets/fonts/montserrat-v12-latin-300.woff') format('woff');
}

/* montserrat-regular - latin */
@font-face {
   font-family: 'Montserrat';
   font-style: normal;
   font-weight: 400;
   font-display: swap;
   src: local('Montserrat Regular'), local('Montserrat-Regular'),
      url('/assets/fonts/montserrat-v12-latin-regular.woff2') format('woff2'),
      url('/assets/fonts/montserrat-v12-latin-regular.woff') format('woff');
}

/* montserrat-500 - latin */
@font-face {
   font-family: 'Montserrat';
   font-style: normal;
   font-weight: 500;
   font-display: swap;
   src: local('Montserrat Medium'), local('Montserrat-Medium'),
      url('/assets/fonts/montserrat-v12-latin-500.woff2') format('woff2'),
      url('/assets/fonts/montserrat-v12-latin-500.woff') format('woff');
}

/* montserrat-600 - latin */
@font-face {
   font-family: 'Montserrat';
   font-style: normal;
   font-weight: 600;
   font-display: swap;
   src: local('Montserrat SemiBold'), local('Montserrat-SemiBold'),
      url('/assets/fonts/montserrat-v12-latin-600.woff2') format('woff2'),
      url('/assets/fonts/montserrat-v12-latin-600.woff') format('woff');
}
```

This allows the following enhancements:

* Preloading of fonts
* Don't need the DNS pre-fetch
* Doesn't need the font loading script

See related PR [#86](https://github.com/samuelfernandez/portfolio/pull/86).
